//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunusEmreYılmaz._95180053.YBS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan_Tanimi
    {
        public int id { get; set; }
        public string Calisan_tc { get; set; }
        public string Calisan_ad { get; set; }
        public string Calisan_soyad { get; set; }
        public string Calisan_gorevi { get; set; }
        public string Calisan_saat_maaliyet { get; set; }
        public string Calisan_aylik_maaliyet { get; set; }
    }
}
