//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunusEmreYılmaz._95180053.YBS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Is_Istasyon_Tanimi
    {
        public int id { get; set; }
        public string Istasyon_kod { get; set; }
        public string Istasyon_aciklama { get; set; }
        public string Hammadde_ambari { get; set; }
        public string Istasyon_maaliyet { get; set; }
    }
}
