//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunusEmreYılmaz._95180053.YBS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operasyon_Tanimi
    {
        public int id { get; set; }
        public string Operasyon_kodu { get; set; }
        public string Toplam_operasyon_suresi { get; set; }
        public string Islem_suresi { get; set; }
        public string Bekleme_suresi { get; set; }
        public string Tasima_suresi { get; set; }
        public string Operasyon_aciklamasi { get; set; }
    }
}
