//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunusEmreYılmaz._95180053.YBS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete_Tanimi
    {
        public int id { get; set; }
        public string Ana_urun_kodu { get; set; }
        public string Recete_aciklama { get; set; }
        public string Satir_sayisi { get; set; }
        public string Recete_miktar { get; set; }
    }
}
